sudo: false
cache: apt
language: cpp

matrix:
  include:
    - env: COMPILER=g++-5
      compiler: g++-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5

before_install:
  - export CXX=$COMPILER
  - which $CXX

script:
  - rm -rf build;
  - mkdir -p build
  - cd ./build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE ../
  - make
