language: c++
sudo: required
services:
  - docker

env:
  - COMPILER=g++-6 BUILD_TYPE=DEBUG
  - COMPILER=g++-7 BUILD_TYPE=DEBUG
  - COMPILER=clang++-3.8 BUILD_TYPE=DEBUG
  - COMPILER=g++-6 BUILD_TYPE=RELEASE
  - COMPILER=g++-7 BUILD_TYPE=RELEASE
  - COMPILER=clang++-3.8 BUILD_TYPE=RELEASE

before_install:
  - docker build -t testing -f ci/toolchain.docker .

script:
  - docker run -v $(pwd):/h265 --env=CXX=$COMPILER --env=BUILD_TYPE=$BUILD_TYPE --workdir=/h265 testing /bin/bash -c "bash ./ci/run.sh"
